# Generated by Django 5.2.17 on 2026-09-03 08:49

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('original_name', models.CharField(blank=True, default='', max_length=512)),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('prompt', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, default='', max_length=32)),
                ('max_new_tokens', models.IntegerField(default=512)),
                ('want_timestamps', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échec')], default='pending', max_length=16)),
                ('progress', models.FloatField(default=0.0)),
                ('stage', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transcript_text', models.TextField(blank=True, default='')),
                ('language_detected', models.CharField(blank=True, default='', max_length=64)),
                ('segments_json', models.TextField(blank=True, default='')),
                ('segment_count', models.IntegerField(default=0)),
                ('generated_tokens', models.IntegerField(blank=True, null=True)),
                ('device', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'verbose_name': 'Transcription',
                'verbose_name_plural': 'Transcriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
