# Generated by Django 5.2.17 on 2026-09-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='corrected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcriptionjob',
            name='corrected_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
