# Generated by Django 5.2.17 on 2026-09-14 07:49

import django.core.validators
import transcriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0002_transcriptionjob_corrected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptionjob',
            name='content_type',
            field=models.CharField(blank=True, default='', help_text='Type MIME du fichier', max_length=128),
        ),
        migrations.AddField(
            model_name='transcriptionjob',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='Taille du fichier en octets', null=True),
        ),
        migrations.AlterField(
            model_name='transcriptionjob',
            name='audio_file',
            field=models.FileField(upload_to=transcriptions.models.audio_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['wav', 'mp3', 'mp4', 'flac', 'm4a', 'ogg', 'opus', 'aac', 'wma', 'mov', 'mkv', 'webm', 'amr'])]),
        ),
    ]
