# Generated by Django 5.2.17 on 2026-09-23 09:52

import transcriptions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcriptions', '0003_transcriptionjob_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptionjob',
            name='audio_file',
            field=models.FileField(upload_to=transcriptions.models.audio_upload_path),
        ),
    ]
